### Run test remotely
# @timeout 120
POST http://77.234.215.138:34321/run
Content-Type: application/json

{
  "serviceName": "AcDc",
  "token": "m2maxfs2763AC10gGp",
  "branch": "hw-1",
  "accounts": "acc-3",
  "ratePerSecond": 11,
  "testCount": 1200,
  "processingTimeMillis": 80000,
  "onPremises": true
}

### Stop running test to save credits
# @timeout 120
POST http://77.234.215.138:31234/test/stop/AcDc