### Run test remotely
# @timeout 120
POST http://77.234.215.138:34321/run
Content-Type: application/json

{
  "serviceName": "AcDc",
  "token": "m2maxfs2763AC10gGp",
  "branch": "hw-12",
  "accounts": "acc-19",
  "ratePerSecond": 100,
  "testCount": 50000,
  "processingTimeMillis": 10000000,
  "onPremises": true
} 

### Stop running test to save credits
# @timeout 120
POST http://77.234.215.138:31234/test/stop/AcDc