### Run test locally
POST http://localhost:1234/test/run
Content-Type: application/json

{
  "serviceName": "AcDc",
  "token": "",
  "ratePerSecond": 3,
  "testCount": 1050,
  "processingTimeMillis": 26000,
  "runits" : 90
}

### Stop running test to save time and resources
# @timeout 120
POST http://localhost:1234/test/stop/AcDc
